In [9]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [4]:
X=np.array([[2,1],[3,1],[1,4],[2,6]])
print(X)

[[2 1]
 [3 1]
 [1 4]
 [2 6]]


# 归一化

In [7]:
scaler=MinMaxScaler()
X_scaled=scaler.fit_transform(X)
print(X_scaled)

[[0.5 0. ]
 [1.  0. ]
 [0.  0.6]
 [0.5 1. ]]


In [8]:
scaler=MinMaxScaler(feature_range=(-1,1))
X_scaled=scaler.fit_transform(X)
print(X_scaled)

[[ 0.  -1. ]
 [ 1.  -1. ]
 [-1.   0.2]
 [ 0.   1. ]]


# 标准化

In [11]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]


In [17]:
mean=np.mean(X,axis=0)
std=np.std(X,axis=0)
print((X-mean)/std)

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]
