In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler,OneHotEncoder,LabelEncoder

In [12]:
label=['本科','大专','博士','硕士','中专','硕士','中专']
label

['本科', '大专', '博士', '硕士', '中专', '硕士', '中专']

## 标签编码

In [6]:
encoder=LabelEncoder()
label_encoded=encoder.fit_transform(label)
label_encoded

array([3, 2, 1, 4, 0, 4, 0])

## 独热编码

In [17]:
label =np.array(label).reshape(-1,1)
label

array([['本科'],
       ['大专'],
       ['博士'],
       ['硕士'],
       ['中专'],
       ['硕士'],
       ['中专']], dtype='<U2')

In [18]:
encoder = OneHotEncoder()
label_encoded=encoder.fit_transform(label,)
print(label_encoded)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (7, 5)>
  Coords	Values
  (0, 3)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 4)	1.0
  (4, 0)	1.0
  (5, 4)	1.0
  (6, 0)	1.0


In [19]:
print(label_encoded.toarray())

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


In [20]:
encoder = OneHotEncoder(sparse_output=False)
label_encoded=encoder.fit_transform(label,)
print(label_encoded)

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
