In [1]:
import torch
import torch.nn as nn

In [2]:
# 定义全连接层
linear=nn.Linear(in_features=2,out_features=3,bias=True)

In [4]:
print('weight',linear.weight)
print('weight',linear.weight.shape)

weight Parameter containing:
tensor([[ 0.0972, -0.4489],
        [ 0.0725,  0.3016],
        [-0.0474,  0.3945]], requires_grad=True)
weight torch.Size([3, 2])


In [5]:
print('bias:',linear.bias)
print('bias:',linear.bias.shape)

bias: Parameter containing:
tensor([-0.5820, -0.5096, -0.6907], requires_grad=True)
bias: torch.Size([3])


In [7]:
# 前向传播
x=torch.tensor([[1,2],[3,4]]).float()
y=linear.forward(x)

In [11]:
print(x.shape)
print(y.shape)
print(x)
print(y)

torch.Size([2, 2])
torch.Size([2, 3])
tensor([[1., 2.],
        [3., 4.]])
tensor([[-1.3826,  0.1660,  0.0508],
        [-2.0861,  0.9140,  0.7449]], grad_fn=<AddmmBackward0>)


In [14]:
y=linear(x)
y

tensor([[-1.3826,  0.1660,  0.0508],
        [-2.0861,  0.9140,  0.7449]], grad_fn=<AddmmBackward0>)