In [3]:
import torch

In [5]:
x=torch.tensor([100.0,3.0,10.0]) # x₁ = 100   房屋面积 房间 数量房龄

In [6]:
# 定义权重
w=torch.tensor([2.0,5.0,-1.0])

In [7]:
# 偏置
b=torch.tensor(10.0)

In [13]:
# z
z=x@w+b
z.sum()

tensor(215.)

In [21]:
import torch
import torch.nn as nn
# 一个线形层
layer=nn.Linear(3,2)
# 一个样本，3个特征
x=torch.tensor([[100.0,3.0,10.0]])
# 前向计算
y=layer(x)
print(y)
print(layer.modules)

tensor([[-7.3017, -6.3177]], grad_fn=<AddmmBackward0>)
<bound method Module.modules of Linear(in_features=3, out_features=2, bias=True)>


In [27]:
layer=nn.Linear(3,2)
x=torch.tensor([[1.0,2.0,3.0]])
y1=layer(x)
print(y1)
y2=x@layer.weight.T+layer.bias
print(y2)

tensor([[-1.0608, -0.0493]], grad_fn=<AddmmBackward0>)
tensor([[-1.0608, -0.0493]], grad_fn=<AddBackward0>)


In [28]:
print(layer.weight)
print(layer.bias)

Parameter containing:
tensor([[-0.2890,  0.3206, -0.4292],
        [ 0.4295, -0.2776, -0.0625]], requires_grad=True)
Parameter containing:
tensor([-0.1254,  0.2640], requires_grad=True)
