In [1]:
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(3, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

x = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

output = model(x)

print(output)

tensor([[0.1849],
        [0.2588]], grad_fn=<AddmmBackward0>)


In [19]:

x = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, -5.0, 116.0]
])
y1=torch.sigmoid(x)
print(y)
tanh=nn.Tanh()
print(tanh(x))
relu=nn.ReLU()
print(relu(x))
leaky_relu=nn.LeakyReLU()
print(leaky_relu(x))
gelu=nn.GELU()
print(gelu(x))
print(nn.Softplus()(x))

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 1.0000]])
tensor([[ 0.7616,  0.9640,  0.9951],
        [ 0.9993, -0.9999,  1.0000]])
tensor([[  1.,   2.,   3.],
        [  4.,   0., 116.]])
tensor([[ 1.0000e+00,  2.0000e+00,  3.0000e+00],
        [ 4.0000e+00, -5.0000e-02,  1.1600e+02]])
tensor([[ 8.4134e-01,  1.9545e+00,  2.9960e+00],
        [ 3.9999e+00, -1.4901e-06,  1.1600e+02]])
tensor([[1.3133e+00, 2.1269e+00, 3.0486e+00],
        [4.0181e+00, 6.7153e-03, 1.1600e+02]])
