In [7]:
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),

    nn.Linear(4, 3),
    nn.ReLU(),

    nn.Linear(3, 1)
)
print(model[0].weight)
y = model(x)
print(model[0].weight) # 和上面完全一样，没有变化

x = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

y = model(x)

# print(y)
# print(y.shape)

Parameter containing:
tensor([[-0.3886,  0.0854],
        [ 0.3354, -0.6794],
        [ 0.0862,  0.4018],
        [ 0.6097, -0.5562]], requires_grad=True)
Parameter containing:
tensor([[-0.3886,  0.0854],
        [ 0.3354, -0.6794],
        [ 0.0862,  0.4018],
        [ 0.6097, -0.5562]], requires_grad=True)


In [6]:
print(model[0].weight)
y = model(x)
print(model[0].weight) # 和上面完全一样，没有变化


Parameter containing:
tensor([[ 0.4653,  0.4871],
        [ 0.5569,  0.2649],
        [ 0.3338, -0.6203],
        [-0.4410, -0.3231]], requires_grad=True)
Parameter containing:
tensor([[ 0.4653,  0.4871],
        [ 0.5569,  0.2649],
        [ 0.3338, -0.6203],
        [-0.4410, -0.3231]], requires_grad=True)
