In [30]:
import torch

x = torch.tensor(2.0, requires_grad=True) # 追踪 x 的计算，并且允许我们计算关于 x 的梯度。

In [35]:
y = x ** 2
y.backward()

In [36]:
print(x.grad)

tensor(12.)


# lalallala

In [58]:
import torch
import torch.nn as nn

In [59]:
model=nn.Linear(1,1)

In [60]:
# 数据
x = torch.tensor([[2.0]])
y=torch.tensor([[10.0]])

In [61]:
# 损失函数
loss_fn=nn.MSELoss()
# 优化器
optimizer=torch.optim.SGD(
    model.parameters(),lr=0.1
)

In [62]:
# 第一次训练
y_pred=model(x)
loss=loss_fn(y_pred,y)
loss.backward()

In [63]:
print(model.weight.grad)
print(model.bias.grad)
print(loss)

tensor([[-40.9909]])
tensor([-20.4955])
tensor(105.0160, grad_fn=<MseLossBackward0>)


In [66]:
optimizer.step()
print(model.weight.grad)
print(model.bias.grad)

tensor([[-40.9909]])
tensor([-20.4955])


In [68]:
optimizer.zero_grad()
print(model.weight.grad)
print(model.bias.grad)

None
None
