In [2]:
import torch
from torch.utils.data import TensorDataset,DataLoader

In [21]:
x=torch.tensor([[1],[2],[3],[4]])
y=torch.tensor([9,8,7,6])
ds=TensorDataset(x,y)

In [22]:
print(ds[0])
print(ds[1])

(tensor([1]), tensor(9))
(tensor([2]), tensor(8))


In [23]:
# DataLoader
train_dl=DataLoader(dataset=ds,batch_size=2,shuffle=True,drop_last=False)
print(x)
print(y)

tensor([[1],
        [2],
        [3],
        [4]])
tensor([9, 8, 7, 6])


In [27]:
for bx ,by in train_dl:
    # print('bx shape:',bx.shape)
    # print('by shape:',by.shape)
    print(bx,by)



tensor([[4],
        [2]]) tensor([6, 8])
tensor([[3],
        [1]]) tensor([7, 9])
