In [68]:
import torch

In [69]:
x=torch.tensor([[2.0,1.0]])
w1=torch.tensor([[0.5,0.2],
                 [0.3,0.8],
                 [-0.5,0.4]])
b1=torch.tensor([0.1,0.2,0.3])

w2=torch.tensor([[0.4,0.6,-0.2],
                 [-0.3,0.5,0.7]])
b2=torch.tensor([0.1,-0.1])
y=torch.tensor([0])

In [70]:
z1=x@ w1.T +b1
print(z1)

tensor([[ 1.3000,  1.6000, -0.3000]])


In [71]:
a1=torch.relu(z1)

In [72]:
print(a1)

tensor([[1.3000, 1.6000, 0.0000]])


In [73]:
z2=a1@ w2.T +b2
print(z2)

tensor([[1.5800, 0.3100]])


In [74]:
p=torch.softmax(z2,dim=1)
print(p)

tensor([[0.7807, 0.2193]])


In [75]:
loss1=-torch.log(p[0,y])
print(loss1)
loss2=-torch.log(p[0,1])
print(loss2)

tensor([0.2475])
tensor(1.5175)


In [76]:
y_onehot=torch.nn.functional.one_hot(y,2)
print(y_onehot)

tensor([[1, 0]])


In [77]:
dz2=p-y_onehot
print(dz2)

tensor([[-0.2193,  0.2193]])


In [78]:
dw2=dz2.T@a1
print(dw2)
db2=dz2.squeeze(0)
print(db2)
da1=dz2@ w2
print(da1)

tensor([[-0.2850, -0.3508, -0.0000],
        [ 0.2850,  0.3508,  0.0000]])
tensor([-0.2193,  0.2193])
tensor([[-0.1535, -0.0219,  0.1973]])


In [79]:
relu_grad=(z1>0).float()
print(relu_grad)

tensor([[1., 1., 0.]])


In [80]:
dz1=da1*relu_grad
print(dz1)

tensor([[-0.1535, -0.0219,  0.0000]])


In [81]:
dw1=dz1.T@x
print(dw1)

tensor([[-0.3070, -0.1535],
        [-0.0439, -0.0219],
        [ 0.0000,  0.0000]])


In [82]:
db1=dz1.squeeze(0)
print(db1)

tensor([-0.1535, -0.0219,  0.0000])


In [83]:
dx=dz1@w1
print(dx)

tensor([[-0.0833, -0.0482]])


In [84]:
lr = 0.1

w1 = w1 - lr * dw1
b1 = b1 - lr * db1

w2 = w2 - lr * dw2
b2 = b2 - lr * db2
print(w1)

tensor([[ 0.5307,  0.2153],
        [ 0.3044,  0.8022],
        [-0.5000,  0.4000]])


In [85]:
x = torch.tensor(2.0, requires_grad=True)

y = x ** 2

In [87]:
x=2
y.backward()
print(x.grad)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [88]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = x ** 2

y.backward()

print(x.grad)

tensor(4.)


In [90]:
y.grad_fn
x.grad_fn