In [1]:
"""
1. 使用 Numpy 创建一个包含 1 到 10 的整数的一维数组，并将其重塑为 2 行 5 列的二维数组。
   提示：重塑方法arr.reshape(形状)

2.创建一个3*4的二维数组，并用[1,5]的随机整数进行填充

3.   zeros()：返回给定形状和类型的新数组，用0填充。
     ones()：返回给定形状和类型的新数组，用1填充。
     empty()：返回给定形状和类型的未初始化的新数组。

4.创建一个数组 统计 平均值 最值 方差  标准差

5.创建一个三行5列的数组进行排序
  指定不同的轴线 查看效果
6.什么是广播机制 要求是什么

7.什么是矩阵乘法 举例说明

 arr3 = np.array([[1, 2, 3]])
 arr4 = np.array([[4], [5], [6]])
"""

'\n1. 使用 Numpy 创建一个包含 1 到 10 的整数的一维数组，并将其重塑为 2 行 5 列的二维数组。\n   提示：重塑方法arr.reshape(形状)\n\n2.创建一个3*4的二维数组，并用[1,5]的随机整数进行填充\n\n3.   zeros()：返回给定形状和类型的新数组，用0填充。\n     ones()：返回给定形状和类型的新数组，用1填充。\n     empty()：返回给定形状和类型的未初始化的新数组。\n\n4.创建一个数组 统计 平均值 最值 方差  标准差\n\n5.创建一个三行5列的数组进行排序\n  指定不同的轴线 查看效果\n6.什么是广播机制 要求是什么\n\n7.什么是矩阵乘法 举例说明\n\n arr3 = np.array([[1, 2, 3]])\n arr4 = np.array([[4], [5], [6]])\n'

1. 使用 Numpy 创建一个包含 1 到 10 的整数的一维数组，并将其重塑为 2 行 5 列的二维数组。
   提示：重塑方法arr.reshape(形状)

In [2]:
import numpy as np

In [5]:
arr1=np.array(range(1,11))
print(arr1)
print(arr1.reshape(2,5))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2.创建一个3*4的二维数组，并用[1,5]的随机整数进行填充

In [7]:
arr1=np.random.randint(1,6,(3,4))
print(arr1)

[[4 3 2 4]
 [1 1 4 1]
 [5 4 3 1]]


3.   zeros()：返回给定形状和类型的新数组，用0填充。
     ones()：返回给定形状和类型的新数组，用1填充。
     empty()：返回给定形状和类型的未初始化的新数组。

In [12]:
arr1=np.zeros((3,4),dtype=int)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [14]:
arr2=np.ones((2,4),dtype=float)
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
arr3=np.empty((5,1),dtype=int)
print(arr3)

[[            0]
 [1973269045040]
 [1973269044960]
 [1973269046080]
 [            0]]


4.创建一个数组 统计 平均值 最值 方差  标准差

In [17]:
arr1=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]


In [23]:
print(arr1.mean())
print(arr1.sum())
print(arr1.max())
print(arr1.min())
print(arr1.var())
print(arr1.std())

4.5
54
8
1
3.9166666666666665
1.9790570145063195


5.创建一个三行5列的数组进行排序
  指定不同的轴线 查看效果

In [33]:
arr1=np.random.randint(0,10,(3,5))
print(arr1)

[[8 2 4 1 0]
 [0 3 8 0 8]
 [7 3 1 6 9]]


In [35]:
print(np.sort(arr1))


[[0 1 2 4 8]
 [0 0 3 8 8]
 [1 3 6 7 9]]


In [37]:
print(np.sort(arr1,axis=0))

[[0 2 1 0 0]
 [7 3 4 1 8]
 [8 3 8 6 9]]


In [38]:
print(np.sort(arr1,axis=1))


[[0 1 2 4 8]
 [0 0 3 8 8]
 [1 3 6 7 9]]


In [39]:
print(np.sort(arr1,axis=-1))

[[0 1 2 4 8]
 [0 0 3 8 8]
 [1 3 6 7 9]]


In [40]:
import pandas as pd
s = pd.Series([11, 22, 22, 44])

print("线性插值 (linear):", s.quantile(0.25, interpolation='linear'))   # 默认值
print("较低值 (lower):"  , s.quantile(0.25, interpolation='lower'))
print("较高值 (higher):" , s.quantile(0.25, interpolation='higher'))
print("最近值 (nearest):", s.quantile(0.25, interpolation='nearest'))
print("中点值 (midpoint):", s.quantile(0.25, interpolation='midpoint'))

线性插值 (linear): 19.25
较低值 (lower): 11
较高值 (higher): 22
最近值 (nearest): 22
中点值 (midpoint): 16.5


In [43]:
df2=pd.DataFrame({"name":["张三","李四","王五"],"age":[10,20,30]})

df2 * 3


,name,age
0,张三张三张三,30
1,李四李四李四,60
2,王五王五王五,90


In [45]:
# df2+'3'

In [46]:
import openpyxl
print("openpyxl 导入成功！版本:", openpyxl.__version__)

# 顺便检查当前内核的 Python 路径（确认是在 data_analysis 环境）
import sys
print("当前解释器路径:", sys.executable)

openpyxl 导入成功！版本: 3.1.5
当前解释器路径: C:\Users\23716\.conda\envs\data_analysis\python.exe
