# ndarray的属性

In [68]:
import numpy as  np

In [2]:
a=np.array([[1,2,3,4],[4,5,6,7]])

In [3]:
print(a)

[[1 2 3 4]
 [4 5 6 7]]


In [4]:
print(a.ndim)

2


In [5]:
print(a.shape)

(2, 4)


In [6]:
print(a.dtype)

int64


In [7]:
print(a.itemsize)

8


In [8]:
print(a.nbytes)

64


# array()和asarray

In [9]:
a=np.array([1,2,3,4])

In [10]:
type(a)

numpy.ndarray

In [11]:
b=np.array(a)


In [12]:
print(id(a))
print(id(b))

2571822956976
2571816175536


In [13]:
a=np.array([1,2,3])
print(id(a))

2571822957456


In [14]:
b=np.asarray(a)
print(id(b))

2571822957456


In [15]:
a=[1,2,3,4]
print(type(a))

<class 'list'>


In [16]:
b=np.array(a)
c=np.asarray(a)
print(id(b))
print(id(c))

2571822957264
2571822957456


# zreos()

In [17]:
arr1=np.zeros((3,5))
arr1
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
arr2=np.ones_like(arr1)
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
arr3=np.empty((3,8))
print(arr3)

[[-0.25 -0.5   0.   -0.25  0.25 -0.5   0.5  -0.25]
 [ 0.25  0.    0.5   0.25  0.25  0.5   0.    0.25]
 [-0.25  0.5  -0.5   0.25 -0.25  0.   -0.5  -0.25]]


In [20]:
arr4=np.empty_like(arr3)
print(arr4)

[[-0.25 -0.5   0.   -0.25  0.25 -0.5   0.5  -0.25]
 [ 0.25  0.    0.5   0.25  0.25  0.5   0.    0.25]
 [-0.25  0.5  -0.5   0.25 -0.25  0.   -0.5  -0.25]]


# full()

In [21]:
arr1=np.full((3,4),'A')
print(arr1)

[['A' 'A' 'A' 'A']
 ['A' 'A' 'A' 'A']
 ['A' 'A' 'A' 'A']]


In [22]:
arr2=np.full_like(arr1,5)
print(arr2)
print(arr2.dtype)

[['5' '5' '5' '5']
 ['5' '5' '5' '5']
 ['5' '5' '5' '5']]
<U1


In [23]:
arr3=np.full_like(arr2,66,int)
print(arr3)
print(arr3.dtype)


[[66 66 66 66]
 [66 66 66 66]
 [66 66 66 66]]
int64


# arange()

In [24]:
arr1=np.arange(0,10,3.15)
print(arr1)

[0.   3.15 6.3  9.45]


In [25]:
arr1=np.linspace(start=0,stop=10,num=5)
print(arr1)

[ 0.   2.5  5.   7.5 10. ]


In [26]:
arr2=np.linspace(0,10,5,endpoint=False)
print(arr2)

[0. 2. 4. 6. 8.]


# 随机数组

In [27]:
arr1=np.random.rand(5,6)
print(arr1)

[[0.26307082 0.55130255 0.47030458 0.92637896 0.37261096 0.52386569]
 [0.02420115 0.71740751 0.76311296 0.11861872 0.07988172 0.09555578]
 [0.26852805 0.07575963 0.7073659  0.16109462 0.31488014 0.67859917]
 [0.61270593 0.48394902 0.82188604 0.21057732 0.29093104 0.43209309]
 [0.49223587 0.7470779  0.08086632 0.34916925 0.57899276 0.77467196]]


In [28]:
arr2=np.random.randint(0,10,(3,4))
print(arr2)

[[2 0 7 5]
 [5 5 7 2]
 [3 2 1 4]]


In [29]:
arr3=np.random.uniform(3,8,(2,3))
print(arr3)

[[4.14462238 6.48393767 5.43832841]
 [4.5083104  6.29751746 4.19986613]]


In [30]:
arr4=np.random.randn(1000)
# print(arr4)
arr4

array([-6.10104582e-02,  1.02758737e+00,  1.07025260e+00,  8.04232190e-01,
       -2.02769096e+00,  1.76612031e+00,  5.52475395e-01, -5.74775621e-01,
        7.27987274e-01,  7.56786952e-01, -4.47284786e-01, -1.56234492e+00,
        1.22829564e+00, -9.58471769e-01,  1.38011486e+00, -1.11436022e+00,
        1.16417178e+00,  1.09966922e+00,  2.61203528e+00, -9.52321347e-01,
       -7.12112248e-01, -3.13111257e-01,  1.89745201e-01, -1.38541976e+00,
       -7.30423279e-01, -1.84681893e-01, -7.52883729e-01, -2.44721156e+00,
        1.60531820e-02,  1.17931230e+00, -3.77288285e-01,  9.04002796e-01,
        1.62895366e+00,  1.22976143e+00, -1.54670677e-01, -1.16263160e+00,
        1.36029120e+00, -1.11325113e+00,  1.83464363e+00, -3.38547992e-01,
       -4.78492753e-01, -2.43114988e+00, -3.78257432e-02, -5.19291157e-01,
        3.93348800e-01,  1.02350400e+00,  1.74805832e+00,  1.76765869e+00,
        3.27543981e-01,  6.84365026e-02,  1.59815645e+00, -7.51084132e-01,
        3.68699860e-01,  

# matrix

In [31]:
arr1=np.matrix("1,2;3,4")
print(arr1)

[[1 2]
 [3 4]]


In [32]:
arr2=np.matrix([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [33]:
arr1=np.matrix("1,2,4;3,4,4;1,2,4")
print(arr1)

[[1 2 4]
 [3 4 4]
 [1 2 4]]


In [34]:
# arr2=np.matrix([[[1,2],[3,5]],[[4,5],[5,6]]])
# print(arr2)

In [35]:
arr1=np.array([1,2,3],dtype=np.float64)
print(arr1)

[1. 2. 3.]


In [36]:
arr2=np.array([1.5,2.5,3.9],dtype=np.int16)
print(arr2)

[1 2 3]


In [37]:
arr3=np.array([1,2,3,4,5],dtype=np.float64)
print(arr3)
arr4=arr3.astype(np.int8)
print(arr4)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


# ndarray切片与索引

In [38]:
arr1=np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
print(arr1[0])

0


In [40]:
print(arr1[slice(1,9,2)])

[1 3 5 7]


In [41]:
print(arr1[1:9:2])

[1 3 5 7]


# numpy常用函数

In [42]:
arr1=np.random.randn(2,3)
print(arr1)

[[-0.47181468 -0.56334197 -0.59589033]
 [-1.04218127  0.16348061 -0.16696719]]


In [43]:
print(np.multiply(arr1,2))

[[-0.94362935 -1.12668394 -1.19178065]
 [-2.08436253  0.32696123 -0.33393438]]


In [44]:
print(np.where(arr1>0,111,00))

[[  0   0   0]
 [  0 111   0]]


In [45]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [46]:
print(np.multiply(arr1,arr2))

[[-0.47181468 -1.12668394 -1.78767098]
 [-4.16872507  0.81740307 -1.00180313]]


In [47]:
arr1=np.random.randint(1,5,(2,3))
print(arr1)

[[4 1 2]
 [4 3 4]]


In [48]:
print(np.mean(arr1))
print(np.sum(arr1))
print(np.argmax(arr1))
print(np.argmin(arr1))
print(np.cumsum(arr1))


3.0
18
0
1
[ 4  5  7 11 14 18]


In [49]:
print(np.cumprod(arr1,axis=0))
print(np.cumprod(arr1,axis=1))

[[ 4  1  2]
 [16  3  8]]
[[ 4  4  8]
 [ 4 12 48]]


## 比较函数 any all

In [50]:
arr1=np.array([1,2,3,4,5])
print(np.array(arr1>3))

[False False False  True  True]


In [51]:
print(np.any(arr1>3))

True


In [52]:
print(np.all(arr1>3))

False


## 排序函数

In [53]:
arr1 = np.random.randint(0,10,(3,3))
print(arr1)

[[3 1 9]
 [2 3 5]
 [4 8 4]]


In [54]:
arr1.sort()
print(arr1)

[[1 3 9]
 [2 3 5]
 [4 4 8]]


In [55]:
print(arr1)

[[1 3 9]
 [2 3 5]
 [4 4 8]]


In [56]:
arr1.sort(axis=0)
print(arr1)

[[1 3 5]
 [2 3 8]
 [4 4 9]]


In [57]:
arr1=np.random.randint(0,10,(3,3))
print(arr1)
print(id(arr1))

[[7 4 2]
 [4 2 0]
 [2 5 3]]
2571843993936


In [58]:
arr2=np.sort(arr1,axis=0)
print(arr2)
print(id(arr2))

[[2 2 0]
 [4 4 2]
 [7 5 3]]
2571843994224


## 去重函数

In [59]:
arr1=np.random.randint(0,5,(3,3))
print(arr1)

[[3 3 1]
 [4 1 2]
 [1 1 0]]


In [60]:
print(np.unique(arr1))

[0 1 2 3 4]


In [61]:
print(arr1)

[[3 3 1]
 [4 1 2]
 [1 1 0]]


# 基本运算


In [62]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])

In [63]:
print(arr1*arr2)

[[ 7 16 27]
 [40 55 72]]


## 矩阵乘法

In [70]:
arr1 =np.array([[1,2,3,],[4,5,6]])
arr2=np.array([[6,5],[4,3],[2,1]])

In [71]:
print(arr1.shape,arr2.shape)

(2, 3) (3, 2)


In [72]:
print(np.dot(arr1,arr2))

[[20 14]
 [56 41]]


In [73]:
print(arr1 @ arr2)

[[20 14]
 [56 41]]
