In [1]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.95543196, 0.47431807, 0.90238822, 0.86310281, 0.82161252])

In [7]:
np.random.randint(0,5,10)# 包头不包尾

array([4, 1, 4, 3, 2, 4, 4, 4, 4, 3], dtype=int32)

In [10]:
c=np.random.randn(2,5)
print(c)

[[-2.21375837 -0.31124428  1.14825105  0.70728144  0.59334514]
 [-0.65590175 -1.18688944  0.23176972  0.52270366 -0.34212604]]
